# Generated by Django 5.1.1 on 2024-11-06 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0002_alter_invoiceitem_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="payment_link",
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("Mobile Money", "Mobile Money"),
                    ("Bank Transfer", "Bank Transfer"),
                    ("PayPal", "PayPal"),
                    ("Payment Link", "Payment Link"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="InvoicePaymentDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("Mobile Money", "Mobile Money"),
                            ("Bank Transfer", "Bank Transfer"),
                            ("PayPal", "PayPal"),
                            ("Payment Link", "Payment Link"),
                        ],
                        max_length=255,
                    ),
                ),
                ("bank_name", models.CharField(max_length=255, null=True)),
                ("account_name", models.CharField(max_length=255, null=True)),
                ("account_number", models.CharField(max_length=255, null=True)),
                ("swift_code", models.CharField(max_length=255, null=True)),
                (
                    "mobile_money_provider",
                    models.CharField(
                        choices=[
                            ("Mpesa Africa", "Mpesa Africa"),
                            ("Airtel Money", "Airtel Money"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                ("mobile_money_code", models.CharField(max_length=255, null=True)),
                ("mobile_money_number", models.CharField(max_length=255, null=True)),
                ("paypal_email", models.EmailField(max_length=254, null=True)),
                ("payment_link", models.URLField(null=True)),
                (
                    "invoice",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoicepaymentdetails",
                        to="invoices.invoice",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
