# Generated by Django 5.1.1 on 2024-11-06 14:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0003_invoice_payment_link_invoice_payment_method_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoicepaymentdetails",
            name="routing_number",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
