# Generated by Django 5.1.1 on 2024-11-06 14:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0004_invoicepaymentdetails_routing_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoicepaymentdetails",
            name="paypal_name",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
