# Generated by Django 5.1.1 on 2024-11-06 15:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0005_invoicepaymentdetails_paypal_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoicepaymentdetails",
            name="payment_link",
        ),
        migrations.AddField(
            model_name="invoicepaymentdetails",
            name="payer_email",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="invoicepaymentdetails",
            name="payer_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="invoicepaymentdetails",
            name="payer_phone_number",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
