# Generated by Django 4.1.1 on 2022-11-13 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='month',
        ),
        migrations.AddField(
            model_name='bill',
            name='budget',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.budget'),
        ),
    ]
