# Generated by Django 4.1.1 on 2022-11-13 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_remove_bill_month_bill_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.budget'),
        ),
    ]
