# Generated by Django 4.1.7 on 2023-05-28 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_bill_amount_saved_budget_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='amount_saved',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
