# Generated by Django 4.1.1 on 2023-03-25 10:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lipia", "0002_alter_mpesaresponsebody_body"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("services", models.JSONField(blank=True, null=True)),
                ("bill_number", models.CharField(max_length=255)),
                ("bill_number_type", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
