# Generated by Django 4.1.7 on 2023-05-26 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lipia', '0003_mpesaauthtoken'),
        ('lipia', '0004_mpesatransaction'),
    ]

    operations = [
    ]
