# Generated by Django 4.1.7 on 2023-06-02 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lipia', '0007_serviceprovider_callback_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='bill_number_type',
            field=models.CharField(choices=[('till_number', 'Till Number'), ('paybill_number', 'Paybill Number')], max_length=255, null=True),
        ),
    ]
