# Generated by Django 4.1.1 on 2023-02-05 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShopStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255)),
                ('starting_stock', models.FloatField(default=0)),
                ('closing_stock', models.FloatField(default=0)),
                ('quantifier', models.CharField(choices=[('kg', 'Kilogram(s)'), ('lt', 'Litre(s)'), ('count', 'Count')], max_length=255)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_date', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='shop.shop')),
            ],
        ),
    ]
