# Generated by Django 5.1.1 on 2024-10-23 16:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0002_chimmoneypaymentrequest_payment_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chimmoneypaymentrequest",
            name="payer_name",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
