# Generated by Django 5.1.1 on 2024-10-10 10:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("loans", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="date_due",
            field=models.DateField(null=True),
        ),
    ]
