# Generated by Django 5.1.1 on 2024-10-10 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("loans", "0005_alter_loaninstallment_user_alter_loanrepayment_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="loanrepayment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("Cash", "Cash"),
                    ("Card", "Card"),
                    ("Cheque", "Cheque"),
                    ("Bank Transfer", "Bank Transfer"),
                    ("Mpesa", "Mpesa"),
                    ("Other", "Other"),
                ],
                default="Mpesa",
                max_length=255,
            ),
        ),
    ]
