# Generated by Django 5.1.1 on 2024-10-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("loans", "0006_loanrepayment_payment_method"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="loanrepayment",
            name="loan_installment",
        ),
        migrations.RemoveField(
            model_name="loan",
            name="number_of_installments",
        ),
        migrations.AddField(
            model_name="loan",
            name="installment",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.DeleteModel(
            name="LoanInstallment",
        ),
    ]
