# Generated by Django 5.1.1 on 2024-10-23 08:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("loans", "0007_remove_loanrepayment_loan_installment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="loanrepayment",
            name="date_paid",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
