# Generated by Django 5.1.1 on 2024-10-07 07:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budgets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="income",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
    ]
