# Generated by Django 5.1.1 on 2024-10-07 07:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budgets", "0002_budget_income"),
    ]

    operations = [
        migrations.RenameField(
            model_name="budgetallocation",
            old_name="amount",
            new_name="amount_allocated",
        ),
        migrations.RemoveField(
            model_name="budgetallocation",
            name="description",
        ),
        migrations.AddField(
            model_name="budgetallocation",
            name="allocation_type",
            field=models.CharField(
                choices=[
                    ("Rent", "Rent"),
                    ("Household", "Household"),
                    ("Food", "Food"),
                    ("Commuting", "Commuting"),
                    ("Family", "Family"),
                    ("Loan Repayments", "Loan Repayments"),
                    ("Entertainment", "Entertainment"),
                    ("Charity and Support", "Charity and Support"),
                    ("Investments", "Investments"),
                    ("Savings", "Savings"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="budgetallocation",
            name="amount_spend",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
    ]
