# Generated by Django 5.1.1 on 2024-10-12 19:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("budgets", "0011_budgetallocation_category_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="budget",
            name="amount_budgeted",
        ),
        migrations.RemoveField(
            model_name="budget",
            name="amount_spend",
        ),
    ]
