# Generated by Django 5.1.1 on 2024-10-12 20:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("budgets", "0012_remove_budget_amount_budgeted_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="budgetallocation",
            name="amount_spend",
        ),
    ]
