# Generated by Django 5.1.1 on 2024-10-10 09:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finances", "0003_incomerecord_payment_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incomerecord",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("Cash", "Cash"),
                    ("Card", "Card"),
                    ("Cheque", "Cheque"),
                    ("Bank Transfer", "Bank Transfer"),
                    ("Mpesa", "Mpesa"),
                    ("Other", "Other"),
                ],
                default="Mpesa",
                max_length=255,
            ),
        ),
    ]
