# Generated by Django 5.1.1 on 2024-10-10 10:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finances", "0004_alter_incomerecord_payment_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="incomerecord",
            name="received_from",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
