# Generated by Django 5.1.1 on 2024-10-11 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finances", "0007_alter_investment_investment_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="investment",
            name="notes",
            field=models.TextField(null=True),
        ),
    ]
