# Generated by Django 5.1.1 on 2024-10-12 19:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finances", "0008_investment_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="expenditure",
            name="description",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
